version: "3"
services:
  data-resource-database:
    image: postgres:11.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data_resource
  data-resource:
    image: brighthive/data-resource-generator:latest
    depends_on:
      - data-resource-database
    environment:
      - APP_ENV=PRODUCTION
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOSTNAME=data-resource-database
      - POSTGRES_DATABASE=data_resource
      - POSTGRES_PORT=5432
      - SCHEMA_STORAGE_TYPE=LOCAL
      - AWS_SM_ENABLED=0
      - AWS_SM_NAME=
      - AWS_SM_REGION=
      - AWS_SM_DBNAME=
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - 8081:8081
    restart: always
